apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nightclazz
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nightclazz
  template:
    metadata:
      labels:
        app: nightclazz
    spec:
      containers:
        - name: nightclazz
          image: gcr.io/google-samples/kubernetes-bootcamp:v1
          imagePullPolicy: Always

          ports:
            - containerPort: 8080
      restartPolicy: Always
